Nn solution
Oskshust/evo_comp pull request #4
Opened 2023-10-14 16:56 UTC by AlicjaKasicka

2023-10-14 17:10 UTC, Oskshust requested changes

2023-10-14 17:10 UTC, Oskshust commented on 1/greedy_heuristics/scripts.py
> +def get_dist_nn_matrix(path: str):
How about adding a boolean option 'with_node_cost' to 'get_dist_matrix' and return distances + costs or just distances?

2023-10-14 17:10 UTC, Oskshust commented on 1/greedy_heuristics/scripts.py
> +    v1 = np.random.choice(matrix.shape[0])
We need a solution for each node. Suggestion - provide starting node as an argument

2023-10-15 17:37 UTC, radswn approved these changes

2023-10-15 19:17 UTC, Oskshust approved these changes

2023-10-15 19:18 UTC, merged